### ISSUE TITLE
Homebridge won't start after replacing files

### ISSUE THREAD

**Issue by npburns224** [EthanRDoesMC/homebridge-sengled-ethanr#1]
TypeError: Cannot read property 'getCharacteristic' of undefined
    at SengledHubPlatform.setService (/home/pi/.npm-global/lib/node_modules/homebridge-sengled/index.js:165:9)
    at SengledHubPlatform.configureAccessory (/home/pi/.npm-global/lib/node_modules/homebridge-sengled/index.js:47:14)
    at Server._configCachedPlatformAccessories (/home/pi/.npm-global/lib/node_modules/homebridge/lib/server.js:386:24)
    at Server.run (/home/pi/.npm-global/lib/node_modules/homebridge/lib/server.js:93:8)
    at module.exports (/home/pi/.npm-global/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/home/pi/.npm-global/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

**Comment by EthanRDoesMC** [comment]
Power went out at my house, I’ll check it whenever I can

**Comment by brewerc1** [comment]
Yeah, same problem here. Don't bother installing unless you enjoy removing all your devices from Homebridge only to have to re-add them when this doesn't work. :-/

Also, your instructions refer to config.js, which doesn't exist.

**Comment by EthanRDoesMC** [comment]
Sorry - forgot all about this. I’m on vacation but I’ll turn it into a proper plugin when I get back.

**Comment by dean1d** [comment]
Any update on this?  It seemed promising until I received the same error everyone else had.  I am trying to debug myself and will let you know if I figure it out.

Nevermind.  I should have followed your instructions.  I think it was cached that the light bulb was a plug from the first install.  I set up the plugin as a child bridge (new to Homebridge 1.3) and it created a new cache that allows for brightness.

**Comment by EthanRDoesMC** [comment]
yeah, this issue is *very much* my fault. I had zero npm experience and was not thinking in a “plugin” mentality. 

I should buy a whiteboard to help me keep track of projects :)
